galaxy_info:
  author: logan
  description: Configure the OS image
  license: Apache2
  min_ansible_version: 1.6.6
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - cloud
    - development
    - openstack
    - yum
    - apt
dependencies: []
